//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152866 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class 103rd_ODST {
        displayName = "[103rd] ODST";
        side = 1;
        flag = "\OD103\data\Logo\103rdFlag.paa";
        icon = "\OD103\data\Logo\103rdFlag.paa";
        priority = 0;
    };
};

class CfgGroups {
    class WEST {

        class 103rd_ODST {
            name = "[103rd] ODST";

            class Infantry {
                name = "Infantry";

            };

            class SpecOps {
                name = "SpecOps";

                class 103rd_customs {
                    name = "[103rd] Customs";
                    side = 1;
                    faction = "103rd_odst";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CAPTAIN";
                        side = 1;
                        vehicle = "103rd_Hellhawk";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "103rd_Gigasus";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "103rd_Cooky";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "103rd_Astro";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "103rd_Rex";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "103rd_Thunder";
                    };
                };

                class b_us_specops_103rd_main_force103rd_mainforce {
                    name = "[103rd] Main Force";
                    side = 1;
                    faction = "103rd_odst";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "103rd_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "103rd_Medic";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "103rd_Marksman";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "103rd_Engineer";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "103rd_Standard";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "103rd_Standard";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "103rd_Standard";
                    };
                };

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class OPTRE_UNSC_ODST_Soldier_TeamLeader;
    class OPTRE_UNSC_ODST_Soldier_TeamLeader_OCimport_01 : OPTRE_UNSC_ODST_Soldier_TeamLeader { scope = 0; class EventHandlers; };
    class OPTRE_UNSC_ODST_Soldier_TeamLeader_OCimport_02 : OPTRE_UNSC_ODST_Soldier_TeamLeader_OCimport_01 { class EventHandlers; };

    class OPTRE_UNSC_ODST_Soldier_Paramedic;
    class OPTRE_UNSC_ODST_Soldier_Paramedic_OCimport_01 : OPTRE_UNSC_ODST_Soldier_Paramedic { scope = 0; class EventHandlers; };
    class OPTRE_UNSC_ODST_Soldier_Paramedic_OCimport_02 : OPTRE_UNSC_ODST_Soldier_Paramedic_OCimport_01 { class EventHandlers; };

    class OPTRE_UNSC_ODST_Soldier_DemolitionsExpert;
    class OPTRE_UNSC_ODST_Soldier_DemolitionsExpert_OCimport_01 : OPTRE_UNSC_ODST_Soldier_DemolitionsExpert { scope = 0; class EventHandlers; };
    class OPTRE_UNSC_ODST_Soldier_DemolitionsExpert_OCimport_02 : OPTRE_UNSC_ODST_Soldier_DemolitionsExpert_OCimport_01 { class EventHandlers; };

    class 103_Dress_Uniform_Gigasus_v;
    class 103_Dress_Uniform_Gigasus_v_OCimport_01 : 103_Dress_Uniform_Gigasus_v { scope = 0; class EventHandlers; };
    class 103_Dress_Uniform_Gigasus_v_OCimport_02 : 103_Dress_Uniform_Gigasus_v_OCimport_01 { class EventHandlers; };


    class 103rd_Gigasus : OPTRE_UNSC_ODST_Soldier_TeamLeader_OCimport_02 {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] Gigasus";
        side = 1;
        faction = "103rd_odst";

        identityTypes[] = {"Kerry","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_UNSC_visor"};

        uniformClass = "103rd_Uniform_ODST_Weapon";

        linkedItems[] = {"103rd_M52_Gigasus_VEST","103rd_Gigasus_Helmet","ItemMap","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVGT_C"};
        respawnlinkedItems[] = {"103rd_M52_Gigasus_VEST","103rd_Gigasus_Helmet","ItemMap","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVGT_C"};

        weapons[] = {"103rd_M7S_Gigasus"};
        respawnWeapons[] = {"103rd_M7S_Gigasus"};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "103rd_RTO_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"103rd_M7S_Gigasus","","","",{},{},""},{},{},{"103rd_Uniform_ODST_Weapon",{}},{"103rd_M52_Gigasus_VEST",{}},{"103rd_RTO_Rucksack",{}},"103rd_Gigasus_Helmet","103rd_ODST_Command",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVGT_C"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class 103rd_Hellhawk : 103rd_Gigasus {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] Hellhawk";
        side = 1;
        faction = "103rd_odst";

        identityTypes[] = {"Kerry","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_UNSC_visor"};

        uniformClass = "103rd_Uniform_ODST_Weapon";

        linkedItems[] = {"103rd_M52_Hellhawk_VEST","103rd_Hellhawk_Helmet","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"103rd_M52_Hellhawk_VEST","103rd_Hellhawk_Helmet","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "103rd_RTO_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"103rd_Uniform_ODST_Weapon",{{"OPTRE_NVGT_C",1}}},{"103rd_M52_Hellhawk_VEST",{}},{"103rd_RTO_Rucksack",{}},"103rd_Hellhawk_Helmet","OPTRE_G_Bandanna_khk",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class 103rd_Cooky : 103rd_Hellhawk {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] Cooky";
        side = 1;
        faction = "103rd_odst";

        identityTypes[] = {"Kerry","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_UNSC_visor"};

        uniformClass = "103rd_Uniform_ODST_Weapon";

        linkedItems[] = {"103rd_M52_Cooky_VEST","103rd_Cooky_Helmet","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"103rd_M52_Cooky_VEST","103rd_Cooky_Helmet","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "103rd_RTO_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"103rd_Uniform_ODST_Weapon",{{"OPTRE_NVGT_C",1}}},{"103rd_M52_Cooky_VEST",{}},{"103rd_RTO_Rucksack",{}},"103rd_Cooky_Helmet","OPTRE_G_Balaclava_TI_blk_F",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class 103rd_Astro : 103rd_Cooky {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] Astro";
        side = 1;
        faction = "103rd_odst";

        identityTypes[] = {"Kerry","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_UNSC_visor"};

        uniformClass = "103rd_Uniform_ODST_Weapon";

        linkedItems[] = {"103rd_M52_Astro_VEST","103rd_Astro_Helmet","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"103rd_M52_Astro_VEST","103rd_Astro_Helmet","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "103rd_RTO_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"103rd_Uniform_ODST_Weapon",{{"OPTRE_NVGT_C",1}}},{"103rd_M52_Astro_VEST",{}},{"103rd_RTO_Rucksack",{}},"103rd_Astro_Helmet","OPTRE_G_Balaclava_TI_blk_F",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class 103rd_Rex : OPTRE_UNSC_ODST_Soldier_Paramedic_OCimport_02 {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] Rex";
        side = 1;
        faction = "103rd_odst";

        identityTypes[] = {"Kerry","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_UNSC_visor"};

        uniformClass = "103rd_Uniform_ODST_Weapon";

        linkedItems[] = {"103rd_M52_Rex_VEST","103rd_Rex_Helmet","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"103rd_M52_Rex_VEST","103rd_Rex_Helmet","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "103rd_MEDIC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"103rd_Uniform_ODST_Weapon",{{"OPTRE_NVGT_C",1}}},{"103rd_M52_Rex_VEST",{}},{"103rd_MEDIC_Rucksack",{}},"103rd_Rex_Helmet","OPTRE_G_Balaclava_TI_blk_F",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class 103rd_Thunder : 103rd_Astro {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] Thunder";
        side = 1;
        faction = "103rd_odst";

        identityTypes[] = {"Kerry","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_UNSC_visor"};

        uniformClass = "103rd_Uniform_ODST_Weapon";

        linkedItems[] = {"103rd_M52_STND_VEST_RTO","103rd_Thunder_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"103rd_M52_STND_VEST_RTO","103rd_Thunder_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter"};

        weapons[] = {"19_UNSC_M392","OPTRE_M6C","OPTRE_Smartfinder"};
        respawnWeapons[] = {"19_UNSC_M392","OPTRE_M6C","OPTRE_Smartfinder"};

        magazines[] = {"15Rnd_762x51_M392","OPTRE_12Rnd_127x40_Mag","Laserbatteries","15Rnd_762x51_M392","OPTRE_12Rnd_127x40_Mag","Laserbatteries"};
        respawnMagazines[] = {"15Rnd_762x51_M392","OPTRE_12Rnd_127x40_Mag","Laserbatteries","15Rnd_762x51_M392","OPTRE_12Rnd_127x40_Mag","Laserbatteries"};

        backpack = "103rd_RTO_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"19_UNSC_M392","","19_UNSC_BR55_LAM","19_UNSC_evosd",{"15Rnd_762x51_M392",15},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","OPTRE_M6C_Scope",{"OPTRE_12Rnd_127x40_Mag",12},{},""},{"103rd_Uniform_ODST_Weapon",{{"MEU_Biofoam_Light",30},{"MEU_Medigel_Light",30},{"ACE_tourniquet",3},{"ACE_morphine",3},{"ACE_epinephrine",3},{"ACE_plasmaIV_250",2},{"OPTRE_NVGT_C",1},{"OPTRE_16Rnd_127x40_Mag_Tracer",4,16}}},{"103rd_M52_STND_VEST_RTO",{{"15Rnd_762x51_M392_HVAP_tracer",20,15}}},{"103rd_RTO_Rucksack",{{"tsp_lockpick",1},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_wirecutter",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_EntrenchingTool",1},{"ACE_HuntIR_monitor",1},{"MA_M8_Smoke_Blue",5,1},{"MA_M8_Smoke_Green",5,1},{"MA_M8_Smoke_Orange",5,1},{"MA_M8_Smoke_Purple",5,1},{"MA_M8_Smoke_Red",5,1},{"MA_M8_Smoke_Yellow",5,1},{"MA_M8_Smoke_White",2,1}}},"103rd_Thunder_Helmet","103rd_ODST_Command",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class 103rd_Standard : OPTRE_UNSC_ODST_Soldier_TeamLeader_OCimport_02 {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] Standard";
        side = 1;
        faction = "103rd_odst";

        identityTypes[] = {"Kerry","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_UNSC_visor"};

        uniformClass = "103rd_Uniform_ODST_Weapon";

        linkedItems[] = {"103rd_M52_STND_VEST_STANDARD","103rd_CH252D_Helmet_Standard","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVGT_C"};
        respawnlinkedItems[] = {"103rd_M52_STND_VEST_STANDARD","103rd_CH252D_Helmet_Standard","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVGT_C"};

        weapons[] = {"TCP_arifle_MA37_F","TCP_hgun_Pistol_M6C2_F","OPTRE_Smartfinder"};
        respawnWeapons[] = {"TCP_arifle_MA37_F","TCP_hgun_Pistol_M6C2_F","OPTRE_Smartfinder"};

        magazines[] = {"TCP_32Rnd_762x51_Mag","TCP_12Rnd_127x30_52_Mag","Laserbatteries","TCP_32Rnd_762x51_Mag","TCP_12Rnd_127x30_52_Mag","Laserbatteries"};
        respawnMagazines[] = {"TCP_32Rnd_762x51_Mag","TCP_12Rnd_127x30_52_Mag","Laserbatteries","TCP_32Rnd_762x51_Mag","TCP_12Rnd_127x30_52_Mag","Laserbatteries"};

        backpack = "103rd_STANDARD_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"TCP_arifle_MA37_F","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","TCP_optic_EVOSJ",{"TCP_32Rnd_762x51_Mag",32},{},""},{},{"TCP_hgun_Pistol_M6C2_F","TCP_muzzle_snds_127_01","TCP_acc_pointer_lam_M6C2","",{"TCP_12Rnd_127x30_52_Mag",12},{},"TCP_bipod_handGuard_M6G2_blk"},{"103rd_Uniform_ODST_Weapon",{{"MEU_Biofoam_Light",30},{"MEU_Medigel_Light",30},{"ACE_tourniquet",3},{"ACE_morphine",3},{"ACE_epinephrine",3},{"OPTRE_c7_remote_throwable_sticky_mag",2,1},{"OPTRE_M9_Frag",3,1},{"MA_M9_Frag_Mag",4,1},{"TCP_12Rnd_127x30_52_Mag",5,12}}},{"103rd_M52_STND_VEST_STANDARD",{{"OPTRE_16Rnd_127x40_Mag_Tracer",2,16},{"OPTRE_32Rnd_762x51_Mag_Tracer",17,32}}},{"103rd_STANDARD_Rucksack",{{"ACE_wirecutter",1},{"ACE_Flashlight_XL50",1},{"ACE_EntrenchingTool",1},{"ACE_plasmaIV_250",2},{"MA_M8_Smoke_White",4,1},{"OPTRE_16Rnd_127x40_Mag_Tracer",5,16},{"OPTRE_32Rnd_762x51_Mag_Tracer",7,32},{"TCP_32Rnd_762x51_Mag",18,32}}},"103rd_CH252D_Helmet_Standard","103rd_ODST_Facewear",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVGT_C"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class 103rd_Medic : OPTRE_UNSC_ODST_Soldier_Paramedic_OCimport_02 {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] Medic";
        side = 1;
        faction = "103rd_odst";

        identityTypes[] = {"Head_Russian","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_UNSC_visor"};

        uniformClass = "103rd_Uniform_ODST_Weapon";

        linkedItems[] = {"103rd_M52_STND_VEST_MEDIC","103rd_CH252D_Helmet_MEDIC","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVGT_C"};
        respawnlinkedItems[] = {"103rd_M52_STND_VEST_MEDIC","103rd_CH252D_Helmet_MEDIC","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVGT_C"};

        weapons[] = {"TCP_srifle_M392_F","TCP_hgun_Pistol_M6C2_F","OPTRE_Smartfinder"};
        respawnWeapons[] = {"TCP_srifle_M392_F","TCP_hgun_Pistol_M6C2_F","OPTRE_Smartfinder"};

        magazines[] = {"TCP_15Rnd_762x51_Mag","TCP_12Rnd_127x30_52_Mag","Laserbatteries","TCP_15Rnd_762x51_Mag","TCP_12Rnd_127x30_52_Mag","Laserbatteries"};
        respawnMagazines[] = {"TCP_15Rnd_762x51_Mag","TCP_12Rnd_127x30_52_Mag","Laserbatteries","TCP_15Rnd_762x51_Mag","TCP_12Rnd_127x30_52_Mag","Laserbatteries"};

        backpack = "103rd_MEDIC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"TCP_srifle_M392_F","TCP_muzzle_flash_762_01","","TCP_optic_EVOSD",{"TCP_15Rnd_762x51_Mag",15},{},""},{},{"TCP_hgun_Pistol_M6C2_F","TCP_muzzle_snds_127_01","TCP_acc_pointer_lam_M6C2","",{"TCP_12Rnd_127x30_52_Mag",12},{},"TCP_bipod_handGuard_M6G2_blk"},{"103rd_Uniform_ODST_Weapon",{{"MEU_Biofoam_Light",30},{"MEU_Medigel_Light",30},{"ACE_tourniquet",3},{"OPTRE_16Rnd_127x40_Mag_Tracer",4,16},{"TCP_15Rnd_762x51_Mag_Dual",13,15}}},{"103rd_M52_STND_VEST_MEDIC",{{"ACE_personalAidKit",1},{"MA_36Rnd_95x40_HPSAP_Mag_Tracer",15,36},{"TCP_12Rnd_127x30_52_Mag",5,12}}},{"103rd_MEDIC_Rucksack",{{"ACE_surgicalKit",1},{"ACE_tourniquet",25},{"ACE_morphine",10},{"MEU_Biofoam_Light",100},{"MEU_PlasmaIV",10},{"MEU_Medigel_Light",100},{"ACE_personalAidKit",1}}},"103rd_CH252D_Helmet_MEDIC","103rd_ODST_Facewear",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVGT_C"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class 103rd_RTO : 103rd_Standard {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] RTO";
        side = 1;
        faction = "103rd_odst";

        identityTypes[] = {"Kerry","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_UNSC_visor"};

        uniformClass = "103rd_Uniform_ODST_Weapon";

        linkedItems[] = {"103rd_M52_STND_VEST_RTO","103rd_CH252D_Helmet_RTO","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVGT_C"};
        respawnlinkedItems[] = {"103rd_M52_STND_VEST_RTO","103rd_CH252D_Helmet_RTO","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVGT_C"};

        weapons[] = {"19_UNSC_M392","OPTRE_M6C","OPTRE_Smartfinder"};
        respawnWeapons[] = {"19_UNSC_M392","OPTRE_M6C","OPTRE_Smartfinder"};

        magazines[] = {"15Rnd_762x51_M392","OPTRE_12Rnd_127x40_Mag","Laserbatteries","15Rnd_762x51_M392","OPTRE_12Rnd_127x40_Mag","Laserbatteries"};
        respawnMagazines[] = {"15Rnd_762x51_M392","OPTRE_12Rnd_127x40_Mag","Laserbatteries","15Rnd_762x51_M392","OPTRE_12Rnd_127x40_Mag","Laserbatteries"};

        backpack = "103rd_RTO_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"19_UNSC_M392","","19_UNSC_BR55_LAM","19_UNSC_evosd",{"15Rnd_762x51_M392",15},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","OPTRE_M6C_Scope",{"OPTRE_12Rnd_127x40_Mag",12},{},""},{"103rd_Uniform_ODST_Weapon",{{"MEU_Biofoam_Light",30},{"MEU_Medigel_Light",30},{"ACE_tourniquet",3},{"ACE_morphine",3},{"ACE_epinephrine",3},{"ACE_plasmaIV_250",2},{"OPTRE_16Rnd_127x40_Mag_Tracer",4,16}}},{"103rd_M52_STND_VEST_RTO",{{"15Rnd_762x51_M392_HVAP_tracer",20,15}}},{"103rd_RTO_Rucksack",{{"tsp_lockpick",1},{"ACE_IR_Strobe_Item",1},{"ItemcTabHCam",1},{"ACE_wirecutter",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_EntrenchingTool",1},{"ACE_HuntIR_monitor",1},{"MA_M8_Smoke_Blue",5,1},{"MA_M8_Smoke_Green",5,1},{"MA_M8_Smoke_Orange",5,1},{"MA_M8_Smoke_Purple",5,1},{"MA_M8_Smoke_Red",5,1},{"MA_M8_Smoke_Yellow",5,1},{"MA_M8_Smoke_White",2,1}}},"103rd_Thunder_Helmet","103rd_ODST_Command",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVGT_C"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class 103rd_Marksman : 103rd_Standard {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] Marksman";
        side = 1;
        faction = "103rd_odst";

        identityTypes[] = {"Kerry","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_UNSC_visor"};

        uniformClass = "103rd_Uniform_ODST_Weapon";

        linkedItems[] = {"103rd_M52_STND_VEST_MARKSMAN","103rd_CH252D_Helmet_MARKSMAN","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVG_MVI"};
        respawnlinkedItems[] = {"103rd_M52_STND_VEST_MARKSMAN","103rd_CH252D_Helmet_MARKSMAN","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVG_MVI"};

        weapons[] = {"19_UNSC_SRS99AM","OPTRE_M6C","OPTRE_Smartfinder"};
        respawnWeapons[] = {"19_UNSC_SRS99AM","OPTRE_M6C","OPTRE_Smartfinder"};

        magazines[] = {"4Rnd_145x114_srs99_apfsds","OPTRE_8Rnd_127x40_Mag","Laserbatteries","4Rnd_145x114_srs99_apfsds","OPTRE_8Rnd_127x40_Mag","Laserbatteries"};
        respawnMagazines[] = {"4Rnd_145x114_srs99_apfsds","OPTRE_8Rnd_127x40_Mag","Laserbatteries","4Rnd_145x114_srs99_apfsds","OPTRE_8Rnd_127x40_Mag","Laserbatteries"};

        backpack = "103rd_MARKSMAN_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"19_UNSC_SRS99AM","","","",{"4Rnd_145x114_srs99_apfsds",4},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"103rd_Uniform_ODST_Weapon",{{"OPTRE_16Rnd_127x40_Mag_Tracer",5,16}}},{"103rd_M52_STND_VEST_MARKSMAN",{{"ACE_tourniquet",3},{"ACE_morphine",3},{"ACE_epinephrine",3},{"MEU_Biofoam_Light",30},{"OPTRE_M9_Frag",4,1},{"4Rnd_145x114_srs99_apfsds",4,4}}},{"103rd_MARKSMAN_Rucksack",{{"4Rnd_145x114_srs99_apfsds",5,4},{"4Rnd_145x114_srs99_hvap",5,4},{"4Rnd_145x114_srs99_heap",5,4}}},"103rd_CH252D_Helmet_MARKSMAN","103rd_ODST_Command",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVG_MVI"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class 103rd_Engineer : OPTRE_UNSC_ODST_Soldier_DemolitionsExpert_OCimport_02 {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] Engineer";
        side = 1;
        faction = "103rd_odst";

        identityTypes[] = {"Head_Russian","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_UNSC_visor"};

        uniformClass = "103rd_Uniform_ODST_Weapon";

        linkedItems[] = {"103rd_M52_STND_VEST_ENGINEER","103rd_CH252D_Helmet_ENGINEER","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVGT_C"};
        respawnlinkedItems[] = {"103rd_M52_STND_VEST_ENGINEER","103rd_CH252D_Helmet_ENGINEER","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVGT_C"};

        weapons[] = {"19_UNSC_br55","OPTRE_M6C","OPTRE_Smartfinder"};
        respawnWeapons[] = {"19_UNSC_br55","OPTRE_M6C","OPTRE_Smartfinder"};

        magazines[] = {"36Rnd_95x40_br_55_tracer","OPTRE_8Rnd_127x40_Mag","Laserbatteries","36Rnd_95x40_br_55_tracer","OPTRE_8Rnd_127x40_Mag","Laserbatteries"};
        respawnMagazines[] = {"36Rnd_95x40_br_55_tracer","OPTRE_8Rnd_127x40_Mag","Laserbatteries","36Rnd_95x40_br_55_tracer","OPTRE_8Rnd_127x40_Mag","Laserbatteries"};

        backpack = "103rd_ENGINEER_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"19_UNSC_br55","","","19_UNSC_br_scope",{"36Rnd_95x40_br_55_tracer",36},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"103rd_Uniform_ODST_Weapon",{{"ACE_EntrenchingTool",1},{"ACE_M26_Clacker",1},{"ACE_wirecutter",1},{"MEU_Biofoam_Light",25},{"MEU_Medigel_Light",25},{"ACE_tourniquet",3},{"ACE_morphine",3},{"ACE_epinephrine",3},{"ACE_plasmaIV_250",2},{"ACE_IR_Strobe_Item",1},{"tsp_lockpick",1},{"ItemcTabHCam",1},{"OPTRE_8Rnd_127x40_Mag_Tracer",3,8}}},{"103rd_M52_STND_VEST_ENGINEER",{{"ACE_DefusalKit",1},{"36Rnd_95x40_br_55_tracer",11,36}}},{"103rd_ENGINEER_Rucksack",{{"MineDetector",1},{"ACE_Fortify",1},{"C7_Remote_Mag",5,1},{"C12_Remote_Mag",2,1}}},"103rd_CH252D_Helmet_ENGINEER","103rd_ODST_Facewear",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVGT_C"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class 103rd_Gigasus_Dress : 103_Dress_Uniform_Gigasus_v_OCimport_02 {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] Gigasus (Dress)";
        side = 1;
        faction = "103rd_ODST";

        identityTypes[] = {"Head_Russian","LanguageGRE_F","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","NoGlasses"};

        uniformClass = "103_Dress_Uniform_Gigasus";

        linkedItems[] = {"ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"103_Dress_Uniform_Gigasus",{{""},{"",1}}},{},{},"","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class 103rd_Bear_Dress : 103rd_Gigasus_Dress {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] Bear (Dress)";
        side = 1;
        faction = "103rd_ODST";

        identityTypes[] = {"Head_Russian","LanguageGRE_F","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","NoGlasses"};

        uniformClass = "103_Dress_Uniform_Bear";

        linkedItems[] = {"ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"103_Dress_Uniform_Bear",{{""},{""}}},{},{},"","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class 103rd_Hellhawk_Dress : 103rd_Gigasus_Dress {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] Hellhawk (Dress)";
        side = 1;
        faction = "103rd_ODST";

        identityTypes[] = {"Head_Russian","LanguageGRE_F","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","NoGlasses"};

        uniformClass = "103_Dress_Uniform_Hellhawk";

        linkedItems[] = {"ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"103_Dress_Uniform_Hellhawk",{{""},{""}}},{},{},"","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class 103rd_Dress : 103rd_Gigasus_Dress {
        author = "LT. Gigasus";
        scope = 2;
        scopeCurator = 2;
        displayName = "[103rd] Dress";
        side = 1;
        faction = "103rd_ODST";

        identityTypes[] = {"Head_Russian","LanguageGRE_F","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","NoGlasses"};

        uniformClass = "103_Dress_Uniform";

        linkedItems[] = {"ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"103_Dress_Uniform",{{""},{""}}},{},{},"","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};